<?php

namespace HeimrichHannot\FormFieldsCollectionBundle\FrontendWidget;

use Contao\FormCheckbox;

class SingleCheckboxWidget extends FormCheckbox
{
    public const TYPE = 'single_checkbox';

    protected $strTemplate = 'form_huh_singleCheckbox';

    public function __get($strKey)
    {
//        switch ($strKey) {
//            case 'label':
//                return null;
//
//        }
        return parent::__get($strKey); // TODO: Change the autogenerated stub
    }

    protected function isChecked($arrOption = [])
    {
        $arrOption['value'] = $this->value;
        return parent::isChecked($arrOption);
    }


}